name: fates
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - fates-emerald=2.0.1
  - tar=1.32
  - binutils=2.35
  - python>=3
  - perl-xml-libxml=2.0132
  - jupyterlab_launcher>=0.5.0
